# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Stir-bowl manipulation task (Isaac-Stir-Bowl).

Single FR3 + Franka-hand robot picks a spoon out of a stand and stirs three
balls inside a bowl. Mirrors the bidex StirBowl scene (bowl + 3 balls at the
same env-local positions and dimensions) but uses our own EE-delta + binary
gripper controller from stack_cube. Assets (spoon / stand / bowl) are
procedural STLs generated by `nautilus/create-task/isaac-stir-bowl/make_assets.py`.
"""

from . import mdp  # noqa: F401 — re-exports task-local helpers
