#!/usr/bin/env bash
# Auto-generated by env-generator (uv backend) — DO NOT HAND-EDIT.
# Re-run via `/nautilus:env-generator` to regenerate.
# Project: IsaacLab    Python: 3.11    isaacsim: 5.1.0 (pip)
#
# Upgraded from 3.10 + binary isaacsim 4.5 to 3.11 + pip isaacsim 5.1
# 2026-05-06: 5.1 wheels are cp311-only; binary install path replaced
# with pip path. Old setup at setup_uv.sh.4.5.bak.
set -euo pipefail

cd "$(dirname "$0")/.."   # cd to repo root

# --- Step 1: prerequisites ---
command -v uv >/dev/null 2>&1 || { echo "[setup_uv] uv not found — install via 'curl -fsSL https://astral.sh/uv/install.sh | sh'" >&2; exit 1; }

# --- Step 2: create venv (idempotent) ---
if [ ! -d .venv ]; then
  uv venv --python 3.11 .venv
else
  echo "[setup_uv] .venv already exists; reusing"
fi

# Activate venv for the rest of this script.
# shellcheck disable=SC1091
source .venv/bin/activate

# --- Step 3: install steps ---
# (system apt) NOT executed — uv backend cannot sudo. Run manually if imports fail:
#     sudo apt install -y cmake build-essential libegl1 libosmesa6 libgl1 libglib2.0-0
uv pip install --upgrade pip
uv pip install 'setuptools<82.0.0'
# torch FIRST (matches IsaacLab 5.1 docs — pin pre-isaacsim).
uv pip install --index-url https://download.pytorch.org/whl/cu128 torch==2.7.0 torchvision==0.22.0
# isaacsim 5.1 from NVIDIA's pip index (replaces the binary install symlink).
# `extscache` keeps the Kit extension cache on first run; `all` pulls every isaacsim sub-package.
uv pip install --extra-index-url https://pypi.nvidia.com 'isaacsim[all,extscache]==5.1.0'
uv pip install toml
# IsaacLab editable install — order matches env-generator detection from this fork's source/.
uv pip install --editable ./source/isaaclab
uv pip install --editable ./source/isaaclab_assets
uv pip install --editable ./source/isaaclab_tasks
uv pip install --editable './source/isaaclab_rl[all]'
uv pip install --editable './source/isaaclab_mimic[all]'
uv pip install --editable ./source/isaaclab_contrib
uv pip install pynvml

# --- Step 4: nautilus extras (logging + experiment tracking + RL deps) ---
uv pip install wandb tensorboardX
uv pip install 'imageio[ffmpeg]'
uv pip install matplotlib
uv pip install hydra-core omegaconf
uv pip install 'stable_baselines3[extra]'

echo "[setup_uv] Done. Activate the venv with: source .venv/bin/activate"
echo "[setup_uv] NOTE: the _isaac_sim binary symlink is no longer used. Pip-installed isaacsim 5.1 resolves automatically; do NOT source _isaac_sim/setup_conda_env.sh anymore."
